name: self_examination
description: A Tool to examine your state of holiness
publish_to: 'none'

version: 0.1.0+6

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  fl_chart: ^1.1.1
  flutter_localization: ^0.3.3
  intl: any
  url_launcher: ^6.2.2
  local_auth: ^2.2.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/self_examination_light_blue.png"

flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
